### ISSUE TITLE
Some confuses about the repository

### ISSUE THREAD

**Issue by slsefe** [csyhhu/L-OBS#1]
I faced some problems and I hope you could give me help after I studied the paper and the codes. 
1. I have run the lenet300-100/LOBS.py several times and the compression ratio always equals to zero even I deleted the generated files except original parameters. It's worth to you that I just modify your code a little. 
2. Could you give a list of the version of packages which your code using. I find the lenet300-100/LOBS.py is likely using python3 and the ResNet 50 using python2. Morely I want to know the other packages version such as numpy, tensorflow and so on. 
Appreciate for you reply!
BaiYin
1-27-2018

Hi BaiYin,

Thanks for using the codes. For the first question, let me have a check. I will update to you asap. For the second question, I am using python2, both in lenet300-100 and ResNet. The only difference maybe whether there is a () after 'print'. I think the update-to-date numpy and tensorflow is fine. If anything things about function deprecated, pls let me know I will update my code.

Shangyu,
1-27-2018

Hi BaiYin,

Sorry for my careless. I think I have solved the problem that compression ratios are all zeros, it is a minor error of using bracket. I have update the lenet300-100/L-OBS.py, pls sync it and you should see the difference. Also you could check your generated prunned weights and calculate the compression ratio in stead of just watch my print info. 
Pls let me know if there is any other problems~
Thanks again for using our code. I will refine the code in Feb using PyTorch. If you are interested, pls notice~

Shangyu,
1-27-2018

**Comment by csyhhu** [comment]
Hi BaiYin,

Thanks for using the codes. For the first question, let me have a check. I will update to you asap. For the second question, I am using python2, both in lenet300-100 and ResNet. The only difference maybe whether there is a () after 'print'. I think the update-to-date numpy and tensorflow is fine. If anything things about function deprecated, pls let me know I will update my code.

Shangyu,
1-27-2018

Hi BaiYin,

Sorry for my careless. I think I have solved the problem that compression ratios are all zeros, it is a minor error of using bracket. I have update the lenet300-100/L-OBS.py, pls sync it and you should see the difference. Also you could check your generated prunned weights and calculate the compression ratio in stead of just watch my print info.
Pls let me know if there is any other problems~
Thanks again for using our code. I will refine the code in Feb using PyTorch. If you are interested, pls notice~

Shangyu,
1-27-2018

**Comment by slsefe** [comment]
Hi Shangyu,

Firstly Very appreciate to your help and the  problem that compression ratios are all zeros is solved now. I'll pursue to study your codes and create a issue to contact with you if there are any questions about the paper and codes.
Thanks again for your help!

BaiYin
1-27-2018
