### ISSUE TITLE
ValueError: GraphDef cannot be larger than 2GB.

### ISSUE THREAD

**Issue by setyawp25** [csyhhu/L-OBS#3]
Hi Shangyu

When I tried your code to calculate Hessian matrix I got the error ValueError: GraphDef cannot be larger than 2GB.

How can I solve the problem?

thanks

Setya W.P

**Comment by csyhhu** [comment]
Hi Setya @setyawp25 

You can set the batch size of input data as a small number, such as 2.

Best regards,
Shangyu

**Comment by setyawp25** [comment]
Dear Shangyu @csyhhu 

I have tried it but it is failed. I run it on CPU mode tensorflow with Server having 112 GB RAM. Does it cause this problem?

Best

Setya W.P

**Comment by csyhhu** [comment]
Hi Setya,
When I did the experiment, the memory cost is about 100GB, so 112 GB may not be very enough. 

You may also set a bigger convolution strides in models/resnet.py for every layer, so that it will reduce the number of patches extracted and reduce the memory cost.

Best,
Shangyu

**Comment by setyawp25** [comment]
Hi Shangyu @csyhhu 

thanks a lot for your kind response.

Best,

Setya WP

**Comment by csyhhu** [comment]
@setyawp25 

You're welcome, pls let me know if it doesn't work.
